export const IPC_CHANNELS = {
  INIT: 'vault:init',
  LIST_VAULTS: 'vault:list-vaults',
  CREATE_PASSWORD: 'vault:create-password',
  UNLOCK: 'vault:unlock',
  LOCK: 'vault:lock',
  CHANGE_PASSWORD: 'vault:change-password',
  DELETE_VAULT: 'vault:delete-vault',
  DELETE_VAULT_ENTRY: 'vault:delete-vault-entry',
  GET_INFO: 'vault:get-info',
  GET_ITEMS: 'vault:get-items',
  ADD_ITEM: 'vault:add-item',
  EDIT_ITEM: 'vault:edit-item',
  REMOVE_ITEM: 'vault:remove-item',
  EXPORT: 'vault:export',
  IMPORT: 'vault:import',
  EXPORT_FILE: 'vault:export-file',
  IMPORT_FILE: 'vault:import-file',
  TOGGLE_FAVORITE: 'vault:toggle-favorite',
  GET_SETTINGS: 'vault:get-settings',
  SAVE_SETTINGS: 'vault:save-settings',
  GET_VAULT_HINT: 'vault:get-vault-hint',
  TOGGLE_HIDDEN: 'vault:toggle-hidden',
  RECOVER: 'vault:recover',
  SAVE_RECOVERY_PHRASE: 'recovery:save-phrase',
  REGENERATE_RECOVERY_PHRASE: 'vault:regenerate-recovery-phrase',
} as const;
